### ISSUE TITLE
Error: Failed to parse block after blockchain ~ 546603

### ISSUE THREAD

**Issue by ub14** [amjuarez/bytecoin#86]
I picked up a pool (Node-cryptonote-pool), and the last byteoind simplevallet. All earned, connected and extracted (miner is work). But when the botecoid reaches block ~ 546603, the following error occurs. When you roll back bytecoin all normally produced, but with ~ 546 603 error appears again. What can be wrong?

> 2017-03-17 01:29:44 [payments] No workers' balances reached the minimum payment threshold
2017-03-17 01:29:53 [api] Stat collection finished: 27 ms redis, 9004 ms daemon
2017-03-17 01:29:53 [api] Broadcasting to 0 visitors and 0 address lookups
2017-03-17 01:29:55 [pool] (Thread 1) New block to mine at height 1222720 w/ difficulty of 46961927
2017-03-17 01:29:55 [pool] (Thread 1) Started server listening on port 5555
2017-03-17 01:30:12 [pool] (Thread 2) New block to mine at height 1222720 w/ difficulty of 46961927
2017-03-17 01:30:12 [pool] (Thread 2) Started server listening on port 5555
2017-03-17 01:30:14 [unlocker] No blocks candidates in redis

> Error: Failed to parse block
at Object.BlockTemplate.nextBlob (/home/ub14/poolx/lib/pool.js:128:23)
at Object.Miner.getJob (/home/ub14/poolx/lib/pool.js:301:41)`
at handleMinerMethod (/home/ub14/poolx/lib/pool.js:510:28)
at handleMessage (/home/ub14/poolx/lib/pool.js:644:13)
at Socket.socket.on.on.on.pushMessage (/home/ub14/poolx/lib/pool.js:698:25)
at Socket.EventEmitter.emit (events.js:95:17)
at Socket. (stream_readable.js:746:14)
at Socket.EventEmitter.emit (events.js:92:17)
at emitReadable (_stream_readable.js:408:10)
at emitReadable (_stream_readable.js:404:5)

> 2017-03-17 01:30:37 [master] Pool fork 2 died, spawning replacement worker...
2017-03-17 01:30:42 [pool] (Thread 1) New block to mine at height 1222721 w/ difficulty of 47045153
2017-03-17 01:30:42 [api] Stat collection finished: 6 ms redis, 43443 ms daemon
2017-03-17 01:30:42 [api] Broadcasting to 0 visitors and 0 address lookups
2017-03-17 01:30:44 [unlocker] No blocks candidates in redis

**Comment by pmitchev** [comment]
This pool software does not support v3 blocks in the bytecoin blockchain. Use this one instead:
https://github.com/forknote/forknote-pool
